---
server:
  port: 8080

logging.level:
  org.springframework.security: DEBUG

spring:
  security:
    oauth2:
      client:
        registration:
          sso:
            client-id: "fd85860d-fca0-4276-aa7f-ce2a3baeeb57"
            client-secret: "cf9961c8-0938-44ea-8f66-1fb2438759b1"
            authorization-grant-type: "authorization_code"
            client-name: "sso"
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            # NOTE: scope must explicitly be defined or else spring security will request a predefined list of scopes
            # 'email' or 'profile' is required to access the "/userinfo" endpoint via DefaultOidcUser
            scope: "openid,email,todo.read,todo.write"
        provider:
          sso:
            # NOTE: ONLY the 'issuer-uri' must be specified in the 'provider sso' configuration.
            # This ensures that the Principal is OIDCUser instance, which is required to get the ID Token and UserInfo Endpoint data.
            issuer-uri: "https://demo.uaa.run.pivotal.io/oauth/token"
            authorization-uri: "https://demo.login.run.pivotal.io/oauth/authorize"

ssoServiceUrl: "https://demo.login.run.pivotal.io"
